# Generated by Django 4.0.2 on 2022-02-17 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioDatabase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobbies',
            name='h_image',
            field=models.CharField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSVsf9a8CMJ07MTLXvICC1qn8EkFqbZaacuww&usqp=CAU', max_length=500),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='p_image',
            field=models.CharField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQWJYOlsYxx93OW2G8M30CE83UGgTWbcZKObA&usqp=CAU', max_length=500),
        ),
    ]
